language: scala

sudo: false

jdk:
  - oraclejdk8

scala:
  - 2.11.7

script:
  - rm -rf src/main/g8/test
  - sbt ";set G8Keys.properties in G8Keys.g8 in Test ~= { _ + (\"scala_version\" -> \"$TRAVIS_SCALA_VERSION\")}; g8Test"

